name: tiptrick_game
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  device_info_plus: ^4.0.0
  package_info_plus: ^1.4.0
  network_info_plus: ^2.1.3
  encrypt: ^5.0.0
  connectivity_plus: ^2.3.7
  flutter_svg: ">=0.23.0+1 <2.0.0"
  flutter_spinkit:
  hive_flutter: ^1.1.0
  firebase_remote_config: ^3.0.15
  camera: ^0.10.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
